documentation:
  - changed-files:
      - any-glob-to-any-file: "*.md"
cache:
  - changed-files:
      - any-glob-to-any-file: ["src/query/*.rs", "src/commands/*.rs"]
ci:
  - changed-files:
      - any-glob-to-any-file:
          [".github/**/*", "release.config.cjs", "package.json"]
core:
  - changed-files:
      - any-glob-to-any-file: ["src/lib.rs", "Cargo.toml"]

feature:
  - head-branch: ["^feature", "feature"]

fix:
  - head-branch: ["^fix", "fix"]

chore:
  - head-branch: ["^chore", "chore"]
