[package]
name = "famcache"
version = "1.0.0"
description = "Official Famcache server client"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.37.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4"] }
